name = "jinrishan-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[routes]]
pattern = "jinrishan.95sang.cn/api/*"
zone_name = "95sang.cn"

[vars]
ENV = "development"
JWT_SECRET = "dev-secret-change-in-production"
MOONSHOT_API_KEY = "sk-GiFrnfPJBNg9cdH8V6wrQhwxuzUViSFSquLaZbWVyCxzun4s"
CLOUDINARY_CLOUD_NAME = "dtilsnqza"
CLOUDINARY_API_KEY = "671225962841687"
CLOUDINARY_API_SECRET = "l07upYa-iSaUQTGmMpXcJWOUlB0"

[[d1_databases]]
binding = "DB"
database_name = "jinrishan"
database_id = "522c66b3-b556-418c-9e2b-e8b88ac1905c"
migrations_dir = "migrations"
